apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  sources:
    # - repoURL: "https://github.com/rubentest/argocd-manifests.git"
    #   targetRevision: main
    #   ref: values
    - repoURL: "https://charts.bitnami.com/bitnami"
      chart: wordpress
      targetRevision: 24.2.9
      # helm:
      #   valueFiles:
      #     - $values/base/prometheus/values.yaml